apiVersion: v1
kind: Service
metadata:
  name: rekogniz-app-client-user-loadbalancer
  namespace: dev-backend
spec:
  type: LoadBalancer
  selector:
    app: rekogniz-app-client-user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501