apiVersion: v1
kind: Service
metadata:
  name: rekogniz-app-client-user
  namespace: dev-backend
spec:
  selector:
    app: rekogniz-app-client-user
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP